### ISSUE TITLE
Practica de estructura y lectura 

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-equipo-yceee#1]
[Practica de estrutura y lectura.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-equipo-yceee/files/15279425/Practica.de.estrutura.y.lectura.pdf)

**Comment by josealfredo79** [comment]
Se necesita la calificación

**Comment by josealfredo79** [comment]
Calificacion 19
